---
title: "Michigan COVID-19 Mapping"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: yeti
    navbar:
      - {title: explorables, align: right}
      - {title: reports, align: right}
      - {title: publciations, align: right}
      - {title: about us, align: right}
    runtime: shiny
    
---

```{r setup, include=FALSE}

library(ggplot2)
library(plotly)
library(plyr)
library(readr)
library(deSolve)

library(flexdashboard)
library (shiny)

load('Workspace2020-04-25-1587832621.RData')

# Convert times to date format for convenience
dates = startdate + ftimes
casedates = startdate + times

lastdate = tail(casedates, 1)

# Turn off scientific notation on all axes (scipen = 0 turns it back on)
options(scipen=99)

# Convert dates from ggplot numeric to plotly numeric
dt = function(dates){as.numeric(as.POSIXct(dates)*1000)}

```

Inputs {.sidebar}
-----------------------------------------------------------------------

<a href="#"> Michigan Data </a>

<a href="#"> University of Michigan Data </a>


Row {data-height=300}
-----------------------------------------------------------------------

### One Week Forecast of COVID-19 Cases in Michigan

```{r}


```

Row {data-height=300}
-----------------------------------------------------------------------
### Three Week Forecast of COVID-19 Cases in Michigan

```{r}

```

Row {data-height=500}
-----------------------------------------------------------------------


### Summary

*Updated `r format(Sys.time(), "%B %e, %Y at %H:%M %Z")`*